const portfolioData = [
  {
    title: 'Meme Generator',
    screenshot: 'images/meme-generator.png',
    description: 'A simple web app built with React.',
    gitRepo: 'https://github.com/sweenejp/meme-generator',
    liveSite: 'https://jsweeney-meme-generator.netlify.app/',
    display: true,
    tags: ['React'],
  },
  {
    title: 'Social Dashboard',
    screenshot: 'images/social-dashboard.png',
    description: 'Single page web app with a theme-switcher toggle.',
    gitRepo: 'https://github.com/sweenejp/social-media-dashboard',
    liveSite: 'https://jasweeney-social-media-dashboard.netlify.app/',
    display: true,
    tags: ['Featured', 'React', 'SASS'],
  },
  {
    title: 'Sunnyside Agency Page',
    screenshot: 'images/sunnyside-agency-page.png',
    description: 'A landing page for a marketing agency.',
    gitRepo: 'https://github.com/sweenejp/sunnyside-agency-landing-page',
    liveSite: 'https://jsweeney-sunnyside-agency-landing-page.netlify.app/',
    display: true,
    tags: ['Featured', 'SASS'],
  },
  {
    title: 'Four Card Feature Section',
    screenshot: 'images/four-card-feature-section.png',
    description:
      'Card elements built with just HTML and CSS. Responsive and mobile-first design.',
    gitRepo: 'https://github.com/sweenejp/four-card-feature-section',
    liveSite: 'https://jsweeney-four-card-feature-section.netlify.app/',
    display: true,
    tags: ['HTML/CSS'],
  },
  {
    title: 'Question Logger',
    screenshot: 'images/question-logger.png',
    description: 'A simple app built with React',
    gitRepo: 'https://github.com/sweenejp/question-logger',
    liveSite: 'https://jsweeney-question-logger.netlify.app/',
    display: true,
    tags: ['React'],
  },
  {
    title: 'Apparel Coming Soon Page',
    screenshot: 'images/base-apparel-coming-soon.png',
    description:
      "A sample 'coming soon' page for an apparel company. Features some simple form validation.",
    gitRepo: 'https://github.com/sweenejp/base-apparel-coming-soon-page',
    liveSite: 'https://jsweeney-base-apparel-coming-soon-page.netlify.app/',
    display: true,
    tags: ['SASS'],
  },
  {
    title: 'Social Proof Section',
    screenshot: 'images/social-proof-section.png',
    description: 'An example of an intricate layout using just HTML and CSS.',
    gitRepo: 'https://github.com/sweenejp/social-proof-section',
    liveSite: 'https://jsweeney-social-proof-section.netlify.app/',
    display: true,
    tags: ['HTML/CSS'],
  },
  {
    title: 'Huddle Landing Page',
    screenshot: 'images/huddle-landing-page.png',
    description:
      "A sample landing page with 'mobile-first' design and responsive layout.",
    gitRepo: 'https://github.com/sweenejp/huddle-landing-page',
    liveSite: 'https://jsweeney-huddle-landing-page.netlify.app/',
    display: true,
    tags: ['HTML/CSS'],
  },
  {
    title: 'Single Price Component',
    screenshot: 'images/single-price-component.png',
    description:
      "A sample price component with 'mobile-first' design and responsive layout.",
    gitRepo: 'https://github.com/sweenejp/single-price-grid-component',
    liveSite: 'https://jsweeney-single-price-grid-component.netlify.app/',
    display: true,
    tags: ['HTML/CSS'],
  },
  {
    title: 'Profile Card Component',
    screenshot: 'images/profile-card-component.png',
    description: 'A sample profile card component.',
    gitRepo: 'https://github.com/sweenejp/profile-card-component',
    liveSite: 'https://jsweeney-profile-card-component.netlify.app/',
    display: true,
    tags: ['HTML/CSS'],
  },
  {
    title: 'IP Address Tracker',
    screenshot: 'images/ip-address-tracker.png',
    description: 'A web app that returns data about IP addresses',
    gitRepo: 'https://github.com/sweenejp/ip-address-tracker',
    liveSite: 'https://jsweeney-ip-address-tracker.netlify.app/',
    display: true,
    tags: ['Featured'],
  },
  {
    title: 'Coffeeroasters Subscription Site',
    screenshot: 'images/coffeeroasters-subscription-site.png',
    description:
      'A three page website with an order form built with React functional components',
    gitRepo: 'https://github.com/sweenejp/coffeeroasters-subscription-site',
    liveSite: 'https://jsweeney-coffeeroasters-subscription-site.netlify.app/',
    display: true,
    tags: ['React', 'Styled-components', 'Featured'],
  },
  {
    title: 'Ecommerce Product Page',
    screenshot: 'images/ecommerce-product-page.jpg',
    description: 'Sample page of an ecommerce store',
    gitRepo: 'https://github.com/sweenejp/ecommerce-product-page',
    liveSite: 'https://jsweeney-ecommerce-product-page.netlify.app/',
    display: true,
    tags: ['React', 'Styled-components', 'Featured'],
  },
  {
    title: 'App Landing Page',
    screenshot: 'images/fishing-app.png',
    description: 'A landing page for a fishing app',
    liveSite: 'https://catchjournal.app/static/home-page/index.html',
    display: true,
    tags: ['React', 'HTML/CSS'],
  },
];

export default portfolioData;
